# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-07 07:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('cate', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('artical', models.TextField()),
                ('img', models.ImageField(upload_to=b'')),
            ],
        ),
    ]
