# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-10 05:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
